name: Deploy ke Production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create temp .env for build
        run: |
          echo "APP_NAME=pos" > .env
          echo "APP_ENV=production" >> .env
          echo "APP_KEY=base64:gbiKwHRSQv7Xm59H3uTE486fAXXvAYwLYSql+51aCSM=" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "CACHE_STORE=file" >> .env
          echo "SESSION_DRIVER=file" >> .env

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Build Vite
        run: |
          npm ci
          npm run build

      - name: Upload ke production
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 45022
          source: "public/build,vendor"
          target: "~/public_html/kantin-management"

      - name: SSH Deploy ke Production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 45022
          script: |
            cd ~/public_html/kantin-management || exit 1
            git fetch origin
            git reset --hard origin/main
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate --force
            chmod -R 775 storage bootstrap/cache
            echo "===== PRODUCTION DEPLOY SELESAI ====="